//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalovTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int ExerciseId { get; set; }
        public int Day { get; set; }
        public System.TimeSpan StarHour { get; set; }
        public string Name { get; set; }
        public System.TimeSpan EndHour { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual File File { get; set; }
    }
}
